#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost/test?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: test
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=MySQL
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    defer-datasource-initialization: true